use cardb;

DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS ReturnRecord;
DROP TABLE IF EXISTS ViolationRecord;
DROP TABLE IF EXISTS RentalRecord;
DROP TABLE IF EXISTS Car;
DROP TABLE IF EXISTS CarModel;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS systemlog;
DROP TABLE IF EXISTS administrator;