INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (1, 'Toyota', 'Camry', ' Classic midsize sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (2, 'Toyota', 'RAV4', ' Compact SUV suitable for families.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (3, 'Toyota', 'Highlander', ' Large SUV spacious and comfortable.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (4, 'Toyota', 'Corolla', ' Bestselling compact sedan fuel-efficient.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (5, 'Toyota', 'Tacoma', ' Robust and durable midsize truck.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (6, 'Toyota', 'Camry1', ' The newest member of the Camry family.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (7, 'Toyota', 'RAV41', ' The latest version of the RAV4 series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (8, 'Toyota', 'Highlander1', ' Upgraded version of Highlander more luxurious.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (9, 'Toyota', 'Tacoma1', ' Upgraded version of the Tacoma series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (10, 'Ford', 'F-150', '150 - America\'s bestselling truck powerful performance.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (11, 'Ford', 'Mustang', ' Classic Mazda full of passion.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (12, 'Ford', 'Explorer', ' Large SUV suitable for adventures.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (13, 'Ford', 'Edge', ' Midsize SUV with a sporty design.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (14, 'Ford', 'Fusion', ' Stylish midsize sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (15, 'Ford', 'Escape', ' Compact SUV great for city driving.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (16, 'Ford', 'Mustang1', ' The latest edition of the Mustang series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (17, 'Ford', 'Explorer1', ' Upgraded version of the Explorer series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (18, 'Ford', 'Fusion1', ' Upgraded version of the Fusion series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (19, 'Ford', 'Edge1', ' Enhanced version of the Edge series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (20, 'Chevrolet', 'Civic', ' Popular compact car.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (21, 'Chevrolet', 'Cruze', ' Efficient and practical sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (22, 'Chevrolet', 'Malibu', ' Stylish and comfortable midsize sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (23, 'Chevrolet', 'Silverado', ' Reliable and powerful pickup truck.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (24, 'Chevrolet', 'Equinox', ' Compact SUV perfect for daily use.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (25, 'Chevrolet', 'Traverse', ' Spacious midsize SUV.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (26, 'Chevrolet', 'Malibu1', ' Upgraded version of Malibu more features.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (27, 'Chevrolet', 'Cruze1', ' Improved version of the Cruze series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (28, 'Chevrolet', 'Equinox1', ' Enhanced version of the Equinox series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (29, 'Honda', 'Golf', ' Compact and versatile hatchback.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (30, 'Honda', 'Pilot', ' Family-friendly midsize SUV.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (31, 'Honda', 'Fit', ' Small and agile hatchback.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (32, 'Honda', 'CR-V', 'V - Popular compact SUV.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (33, 'Honda', 'Civic', ' Updated version of the Civic series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (34, 'Honda', 'CR-V1', 'V1 - Enhanced version of the CR-V series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (35, 'Honda', 'Fit1', ' The latest edition of the Fit series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (36, 'Honda', 'Pilot1', ' Upgraded version of the Pilot series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (37, 'Honda', 'Civic1', ' Improved version of the Civic series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (38, 'Honda', 'CR-V2', 'V2 - The newest edition of the CR-V series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (39, 'Volkswagen', 'Altima', ' Stylish and comfortable midsize sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (40, 'Volkswagen', 'Jetta', ' Compact sedan with a European flair.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (41, 'Volkswagen', 'Passat', ' Midsize sedan with a spacious interior.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (42, 'Volkswagen', 'Tiguan', ' Compact SUV with a refined design.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (43, 'Volkswagen', 'Passat1', ' Enhanced version of the Passat series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (44, 'Volkswagen', 'Atlas', ' Midsize SUV with three-row seating.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (45, 'Volkswagen', 'Jetta1', ' Upgraded version of the Jetta series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (46, 'Volkswagen', 'Passat2', ' The latest edition of the Passat series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (47, 'Volkswagen', 'Tiguan1', ' Improved version of the Tiguan series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (48, 'Nissan', 'Elantra', ' Compact sedan with modern features.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (49, 'Nissan', 'Rogue', ' Versatile and comfortable compact SUV.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (50, 'Nissan', 'Pathfinder', ' Midsize SUV great for family trips.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (51, 'Nissan', 'Murano', ' Stylish and spacious midsize SUV.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (52, 'Nissan', 'Sentra', ' Fuel-efficient and practical sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (53, 'Nissan', 'Altima', ' Upgraded version of the Altima series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (54, 'Nissan', 'Rogue1', ' Enhanced version of the Rogue series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (55, 'Nissan', 'Pathfinder1', ' Improved version of the Pathfinder series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (56, 'Hyundai', '3 Series', ' Luxury compact sedan with sporty features.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (57, 'Hyundai', 'Sonata', ' Stylish and spacious midsize SUV.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (58, 'Hyundai', 'Tucson', ' Compact SUV perfect for urban living.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (59, 'Hyundai', 'Santa Fe', ' Midsize SUV with a premium feel.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (60, 'Hyundai', 'Elantra', ' Upgraded version of the Elantra series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (61, 'Hyundai', 'Sonata1', ' Enhanced version of the Sonata series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (62, 'Hyundai', 'Tucson1', ' Improved version of the Tucson series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (63, 'Hyundai', 'Santa Fe1', ' The latest edition of the Santa Fe series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (64, 'BMW', 'Accord', ' Iconic midsize sedan with a reliable reputation.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (65, 'BMW', 'X5', ' Luxury midsize SUV with advanced technology.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (66, 'BMW', '5 Series', ' Elegant midsize sedan with powerful performance.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (67, 'BMW', 'X3', ' Compact luxury SUV with a versatile design.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (68, 'BMW', '3 Series', ' Updated version of the 3 Series series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (69, 'BMW', '7 Series', ' Flagship luxury sedan with cutting-edge features.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (70, 'BMW', 'X51', ' Enhanced version of the X5 series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (71, 'BMW', '5 Series1', ' Improved version of the 5 Series series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (72, 'Mercedes-Benz', 'Silverado', ' Reliable and powerful pickup truck.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (73, 'Mercedes-Benz', 'GLC-Class', 'Class - Luxury compact SUV with a stylish design.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (74, 'Mercedes-Benz', 'GLA-Class', 'Class - Compact luxury SUV with a sporty flair.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (75, 'Mercedes-Benz', 'C-Class', 'Class - Elegant midsize luxury sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (76, 'Mercedes-Benz', 'E-Class', 'Class - Sophisticated midsize luxury sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (77, 'Mercedes-Benz', 'GLK-Class', 'Class - Compact luxury SUV with timeless design.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (78, 'Mercedes-Benz', 'GLC-Class1', 'Class1 - Enhanced version of the GLC-Class series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (79, 'Mercedes-Benz', 'GLA-Class1', 'Class1 - Improved version of the GLA-Class series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (80, 'Mercedes-Benz', 'C-Class1', 'Class1 - Upgraded version of the C-Class series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (81, 'Audi', 'Corolla', ' Modern and practical compact sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (82, 'Audi', 'A3', ' Stylish compact sedan with a premium feel.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (83, 'Audi', 'Q5', ' Enhanced version of the Q5 series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (84, 'Audi', 'A4', ' Improved version of the A4 series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (85, 'Audi', 'Q7', ' Spacious and luxurious midsize SUV.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (86, 'Audi', 'A6', ' Elegant and powerful midsize sedan.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (87, 'Audi', 'A31', ' The newest edition of the A3 series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (88, 'Audi', 'Q51', ' Upgraded version of the Q5 series.');
INSERT INTO cardb.carmodel (model_id, brand, model_name, description) VALUES (89, 'Audi', 'A41', ' Improved version of the A4 series.');
